### ISSUE TITLE
Level Sets - Show set name in level chooser menu

### ISSUE THREAD

**Issue by pgerke** [pgerke/nabokos#42]
I think we should show the set name in the level chooser menu. What do you think, @michix99

**Comment by michix99** [comment]
You mean the menu for choosing the level by number from a specific level set? Good point, definitely. We should also think about adding a menu or some sort of level set selection for the Highscore. Going to a specific level is quite annoying right now.

**Comment by pgerke** [comment]
> You mean the menu for choosing the level by number from a specific level set? Good point, definitely.

Yes, exactly. 

> We should also think about adding a menu or some sort of level set selection for the Highscore. Going to a specific level is quite annoying right now.

I agree completely.
